### ISSUE TITLE
[Feature Request] Force 4K assets like Metaphor Essentials

### ISSUE THREAD

**Issue by Foul-Tarnished** [Lyall/MetaphorFix#90]
Could you do add the same feature that [Metaphor Essentials](https://www.nexusmods.com/metaphorrefantazio/mods/5) has ?

I'm not a huge fan of Reloaded-II mods, and they suddenly make my game crash for some reason

**Comment by Lyall** [comment]
As I described in #3, I don't think this is necessary. Adjusting the "texture quality" setting in-game to high will enable the use of 4K assets. It appears to apply just fine regardless of your game resolution and display capabilities. 

If anyone can point out a good reason to override it, I'd be happy to implement that, otherwise it's not an option worth adding.
